apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fulfillment-api
  labels:
    app.kubernetes.io/name: fulfillment-api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fulfillment-api
